id: A68D92948
title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
type: translation
pechas:
- I5B828238
- I7339F74D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:34.347320
  last_modified_at: 2023-01-04 12:12:34.347331
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I5B828238/E522: 0904
  I7339F74D/AEE7: 0904
